# Generated by Django 2.1.2 on 2018-11-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hash_md5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(max_length=32)),
                ('hash_type', models.TextField()),
                ('state', models.TextField()),
                ('time', models.DateTimeField()),
                ('source', models.TextField()),
                ('source_state', models.TextField()),
                ('software', models.TextField()),
                ('tag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='hash_sha128',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(max_length=32)),
                ('hash_type', models.TextField()),
                ('state', models.TextField()),
                ('time', models.DateTimeField()),
                ('source', models.TextField()),
                ('source_state', models.TextField()),
                ('software', models.TextField()),
                ('tag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='hash_sha256',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(max_length=32)),
                ('hash_type', models.TextField()),
                ('state', models.TextField()),
                ('time', models.DateTimeField()),
                ('source', models.TextField()),
                ('source_state', models.TextField()),
                ('software', models.TextField()),
                ('tag', models.TextField()),
            ],
        ),
    ]
